# Generated by Django 4.1.5 on 2023-01-26 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymGeniusApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='workout_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plan', to='gymGeniusApi.workoutplan'),
        ),
    ]
